#!/bin/bash

########## SBATCH Lines for Resource Request ##########

# Def the arguments attributed by the configuration file
FASTA_FILE=$1 #Input
DATABASE_NAME=$2
NUM_JOBS_REPEAT=$3
RMODELER_OUTPUT=$4
RMASKER_OUTPUT=$5
BEDTOOLS_OUTPUT=$6
ISOSEQ3_READS=$7 #input
PBMM2_OUTPUT=$8
ISOSEQ3_OUTPUT=$9
PROTEIN_FILE=$10 #input
DOCKER_IMAGE=$11
LOCAL_DIRECTORY=$12
CONTAINER_DIRECTORY=$13


#--------------------------- REPEAT MODELER
# Use the database name and fasta file from the configuration file
docker run -v /Users/dasilvaf/Genomic_Annotation:/data dfam/tetools:latest BuildDatabase -name /data/$DATABASE_NAME /data/$FASTA_FILE

# Use the database name and number of jobs (threads) from the configuration file
docker run -v /Users/dasilvaf/Genomic_Annotation:/data dfam/tetools:latest RepeatModeler -database /data/$DATABASE_NAME -threads $NUM_JOBS_REPEAT -LTRStruct

#RepeatModeler -database $DATABASE_NAME -threads $NUM_JOBS_REPEAT -LTRStruct &&

#---------------------------- REPEAT MASKER
# Use the output files as input for the next command
docker run -v /Users/dasilvaf/Genomic_Annotation:/data dfam/tetools:latest RepeatMasker -gff -a -pa 16 -u /data/$RMODELER_OUTPUT /data/$FASTA_FILE
#RepeatMasker -gff -a -pa 20 -u $RMODELER_OUTPUT $FASTA_FILE &&

#----------------------------- BEDTOOLS
docker run -v /Users/dasilvaf/Genomic_Annotation:/data pegi3s/bedtools:latest bedtools maskfasta -fi /data/$FASTA_FILE -bed /data/$RMASKER_OUTPUT -soft -fo /data/$BEDTOOLS_OUTPUT
#bedtools maskfasta -fi $FASTA_FILE -bed $RMASKER_OUTPUT -soft -fo $BEDTOOLS_OUTPUT &&

#----------------------------- MAPPING
#Loading modules here to separate fron the other that doesn't depend to the environment
docker run -v /Users/dasilvaf/Genomic_Annotation:/data greensii/isoseq3 pbmm2 align --preset ISOSEQ -O6,24 -B4 --sort /data/$ISOSEQ3_READS /data/$BEDTOOLS_OUTPUT /data/$PBMM2_OUTPUT -j 8
#pbmm2 align --preset ISOSEQ -O6,24 -B4 --sort $ISOSEQ3_READS $BEDTOOLS_OUTPUT $PBMM2_OUTPUT -j 12

docker run -v /Users/dasilvaf/Genomic_Annotation:/data greensii/isoseq3 isoseq3 collapse --do-not-collapse-extra-5exons --min-aln-coverage 0.9 --min-aln-identity 0.95  /data/$PBMM2_OUTPUT /data/$ISOSEQ3_OUTPUT
#docker run greensii/isoseq3 /bin/bash -c isoseq3 collapse --do-not-collapse-extra-5exons --min-aln-coverage 0.9 --min-aln-identity 0.95  /data/TEST2-aligned.bam /data/ISOTEST1.collapsed.gff
