#!/bin/bash

#Setting species name (It will be our reference to next outputs)
SPECIES_NAME="file1.Col-PEK1.5_Chr1-5_20220523" #input

# Name of the database (necessary for repeatmodeler)
DATABASE_NAME=$SPECIES_NAME

# Name of the fasta file
FASTA_FILE="file1.Col-PEK1.5_Chr1-5_20220523.fasta" #input

# Number of parallel jobs in REPEAT process (we can change it later)
NUM_JOBS_REPEAT=36

# Find the repeatmodeler output file
RMODELER_OUTPUT=$SPECIES_NAME-families.fa

# Using repeatmasker output
RMASKER_OUTPUT=$SPECIES_NAME.fasta.out.gff

#Using bedtools output
BEDTOOLS_OUTPUT=$SPECIES_NAME.softmask.fasta

#------------------------------- MAPPING ARGUMENTS
#isoseq3 input
ISOSEQ3_READS="AraTh_Leaves_SRR14584396.fastq" #input

# Using PBMM2 output
PBMM2_OUTPUT=$SPECIES_NAME-aligned.bam
# Using ISOSEQ3 output
ISOSEQ3_OUTPUT=$SPECIES_NAME.collapsed.gff

#-------------------------------- MAKER ARGUMENTS
# Input file for Maker
PROTEIN_FILE="Canola.PROTEINS.faa" #input

VOLUME_NAME="/Users/dasilvaf/Genomic_Annotation"

#-------------------------------- FILTERING ARGUMENTS
SPECIES_ABBREVIATION="AraTh"
STEP1_INPUT=$SPECIES_ABBREVIATION.v01.gff

./pipeline.sh $FASTA_FILE $ISOSEQ3_OUTPUT $RMODELER_OUTPUT $PROTEIN_FILE $VOLUME_NAME $VOLUME_NAME

