#!/bin/bash

SPECIES_ABBREVIATION="AraTh"
FASTA_FILE="file1.Col-PEK1.5_Chr1-5_20220523.fasta"
GLOBAL_GFF="${SPECIES_ABBREVIATION}.v01.gff"
EXCLUDE_LIST="exclude.list"
EXCLUDE_GFF="${SPECIES_ABBREVIATION}.exclude.gff"
UNIQ_GFF="${SPECIES_ABBREVIATION}.uniq.gff"
FINAL_GFF="${SPECIES_ABBREVIATION}.v2.gff"
VOLUME_NAME="/Users/dasilvaf/Downloads/MAKER_OUTPUT"

# # Create global gff
printf "##gff-version 3\n" > "${GLOBAL_GFF}"
tail -n +2 */*maker.output/*_datastore/*/*/*/*gff | awk -F"\t" 'NF==9 && ($3=="gene" || $3 =="CDS" || $3 =="mRNA" || $3 =="exon" || $3 == "five_prime_UTR" || $3 == "three_prime_UTR" || $3 =="tRNA" )' >> "${GLOBAL_GFF}"

# # # # # # # Extract proteins and index
docker run -v "$VOLUME_NAME":/data biodepot/gffread gffread -S -y "/data/${SPECIES_ABBREVIATION}.prots" -g "/data/${FASTA_FILE}" "/data/${GLOBAL_GFF}"
docker run -v "$VOLUME_NAME":/data dbest/samtools:v1.19.2 samtools faidx "/data/${SPECIES_ABBREVIATION}.prots"

# # # Find and process the smallest value
MENOR_VALOR=$(sort -r -k2 -n "${SPECIES_ABBREVIATION}.prots.fai" | cut -f -2 | grep "est2genome" | tail -n 1)
echo "$MENOR_VALOR"
VALUE=$(echo "$MENOR_VALOR" | cut -f2)
echo "$VALUE"
sort -k2 -n AraTh.prots.fai | cut -f -2 | grep protein2genome | awk -v minor="$VALUE" '$2 < minor {print $1}' "${SPECIES_ABBREVIATION}.prots.fai" | sed 's/-mRNA-[0-9]*//' | sort | uniq > exclude.list

# # # # # # Process the rest of your script
printf "#gff-version 3\n" > "${PWD}/${EXCLUDE_GFF}"
docker run -v "$VOLUME_NAME":/data python sh -c "pip install gff3 && python /data/gff_filter.py -e /data/exclude.list -g /data/AraTh.v01.gff >> /data/AraTh.exclude.gff"

docker run -v "$VOLUME_NAME":/data dantestpy1 sh -c "python /data/validate_gff.py --gff /data/${EXCLUDE_GFF} > ${UNIQ_GFF}"

docker run -v "$VOLUME_NAME":/data dantestpy2 sh -c "python /data/renameGff.py -g /data/${UNIQ_GFF} -t /data/${SPECIES_ABBREVIATION} > ${FINAL_GFF}"
